name: Lint
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang-ci lint
        env:
          GOLANGCILINT_VERSION: 1.17.1
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $HOME/bin v${GOLANGCILINT_VERSION}

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint
        run: PATH="$PATH:$HOME/bin" make lint
