name: Tests
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.20", "1.21", "1.22"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/checkout@v2
      - name: Test
        run: make test

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
        id: go
      - uses: actions/checkout@v2
      - name: Benchmark
        run: make bench
